name = "0MFdX"
uuid = "3fb679d3-c3d3-5ab2-b8f9-d1192cd7b3b9"

[deps]
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Graphics = "a2bd30eb-e257-5431-a919-1863eab51364"
Gtk = "4c0ca9eb-093a-5379-98c5-f87ac0bbbf44"
GtkReactive = "27996c0f-39cd-5cc1-a27a-05f136f946b6"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"

[compat]
Cairo = "≥ 0.5.6"
Graphics = "≥ 0.2.0"
GtkReactive = "≥ 0.5.1"
julia = "≥ 0.7.0"
